export const authorBios = [
  "Lifelong nature enthusiast who loves sharing hidden gems with fellow travelers.",
  " avid hiker and weekend warrior. Always looking for the next great view.",
  "Retired park ranger with a passion for conservation and sustainable camping.",
  "Digital nomad living the van life. I know all the best spots with good WiFi and better views.",
  "Full-time RVer traveling the country with my two dogs, Max and Luna.",
  "Just a city slicker trying to escape the concrete jungle whenever I can.",
  "Outdoor photographer chasing sunsets and foggy mornings.",
  "Superhost! I love meeting new people and helping them have the perfect stay.",
  "Adventure seeker, rock climber, and campfire cooking expert.",
  "Family of four exploring the world one campsite at a time.",
  "Solo female traveler empowering others to get out and explore safely.",
  "Kayaking instructor and river guide. Ask me about the best water spots!",
  "Minimalist camper. All you need is a hammock and a good book.",
  "Owner of a small organic farm. Come stay with us and learn about permaculture!",
  "Coffee addict who believes everything tastes better brewed over an open fire.",
  "Stargazer and amateur astronomer. I can show you all the constellations.",
  "Motorcycle camper touring the backroads and scenic byways.",
  "Wilderness First Responder and safety advocate. I value prepared adventures.",
  "History buff who loves exploring campsites near historical landmarks.",
  "Glamping enthusiast. I love nature, but I also love a real mattress.",
  "Part-time host, full-time dad. We love sharing our backyard forest with guests.",
  "Writer and blogger documenting the best campgrounds in the Pacific Northwest.",
  "Survivalist skills instructor. I can teach you how to start a fire without matches.",
  "Yoga teacher who hosts retreats in the wild.",
  "Just here for the s'mores and the ghost stories.",
  "Architect with a love for building unique, off-grid cabins.",
  "Birdwatcher with a life list of over 300 species. Bring your binoculars!",
  "Mushroom forager. If you visit in the fall, I might share my secret spots.",
  "Mountain biker always looking for the best single-track trails.",
  "Former boy scout who never grew out of the camping phase.",
  "Dog lover! All my spots are 100% pet-friendly with fenced areas.",
  "Landscape painter finding inspiration in the quiet corners of the woods.",
  "Musician who loves a good campfire jam session. Bring your guitar!",
  "Sustainable travel advocate trying to leave every place better than I found it.",
  "Local guide born and raised in this area. I know all the shortcuts.",
  "Foodie who plans entire trips around local markets and campfire meals.",
  "Winter camping nut. The cold never bothered me anyway!",
  "Ski bum in the winter, surf bum in the summer.",
  "Teacher on summer break trying to visit every National Park.",
  "I restore vintage Airstreams and rent them out to cool people.",
  "Escape room designer who loves hidden trails and geocaching.",
  "Just looking for peace, quiet, and zero cell service.",
  "Fly fisherman chasing the perfect catch in mountain streams.",
  "Botanist who can name every tree and flower at the campsite.",
  "Marathon runner using camping trips for high-altitude training.",
  "Travel nurse exploring the country between contracts.",
  "Hobby farmer sharing our land with respectful campers.",
  "Tech founder unplugging for the weekend. Don't ask me about crypto.",
  "Podcast host recording episodes from the road.",
  "Believer that the best hotels have 5 billion stars."
];

//done